### ISSUE TITLE
Can you provide some code examples？

### ISSUE THREAD

**Issue by Godlikemandyy** [justindujardin/mathy#96]
I want to achieve a small function, that is, the formula and equation can achieve step by step calculation.But I looked through the documentation and didn't see any code examples, so I didn't know where to start. I hope the author can provide some detailed examples, very grateful!

**Comment by justindujardin** [comment]
Sure, I've got some updates for the main website coming, but in the meantime, you can check out the following:

 - https://core.mathy.ai/ for information on the math tokenizer, parser, rules system, tree layout, builtin rules, etc
 - https://envs.mathy.ai/ for information on the RL side of things, including the built-in environments and how to construct your own

Both of those sites have some inline code examples (that you can run directly) and API documentation about their various classes/modules. They also have their own separate repositories and test suites. They should be a good reference if you want further examples since both projects have high test coverage.

- https://github.com/mathy/mathy_core
- https://github.com/mathy/mathy_envs

**Comment by Godlikemandyy** [comment]
> Sure, I've got some updates for the main website coming, but in the meantime, you can check out the following:
> 
> * https://core.mathy.ai/ for information on the math tokenizer, parser, rules system, tree layout, builtin rules, etc
> * https://envs.mathy.ai/ for information on the RL side of things, including the built-in environments and how to construct your own
> 
> Both of those sites have some inline code examples (that you can run directly) and API documentation about their various classes/modules. They also have their own separate repositories and test suites. They should be a good reference if you want further examples since both projects have high test coverage.
> 
> * https://github.com/mathy/mathy_core
> * https://github.com/mathy/mathy_envs

Thank you very much for your patient guidance, but I find that I cannot complete the following test independently.
I want to implement the following step calculation of the formula, eg: '5+2*3-2*(3-1)', expected output step-by-step:
First step: '5+2*3-4';
Second step: '5+6-4';
Final step: 7;
If I wanted to implement the above example, how would I do it? Please give a detailed code example, thank you！

**Comment by Godlikemandyy** [comment]
> Sure, I've got some updates for the main website coming, but in the meantime, you can check out the following:
> 
> * https://core.mathy.ai/ for information on the math tokenizer, parser, rules system, tree layout, builtin rules, etc
> * https://envs.mathy.ai/ for information on the RL side of things, including the built-in environments and how to construct your own
> 
> Both of those sites have some inline code examples (that you can run directly) and API documentation about their various classes/modules. They also have their own separate repositories and test suites. They should be a good reference if you want further examples since both projects have high test coverage.
> 
> * https://github.com/mathy/mathy_core
> * https://github.com/mathy/mathy_envs

Thank you very much for your patient guidance, but I find that I cannot complete the following test independently.
I want to implement the following step calculation of the formula, eg: `5+2*3-2*(3-1)`, expected output step-by-step:
First step: `5+2*3-4`;
Second step: `5+6-4`;
Final step: 7;
If I wanted to implement the above example, how would I do it? Please give a detailed code example, thank you！

**Comment by Godlikemandyy** [comment]
> Sure, I've got some updates for the main website coming, but in the meantime, you can check out the following:
> 
> * https://core.mathy.ai/ for information on the math tokenizer, parser, rules system, tree layout, builtin rules, etc
> * https://envs.mathy.ai/ for information on the RL side of things, including the built-in environments and how to construct your own
> 
> Both of those sites have some inline code examples (that you can run directly) and API documentation about their various classes/modules. They also have their own separate repositories and test suites. They should be a good reference if you want further examples since both projects have high test coverage.
> 
> * https://github.com/mathy/mathy_core
> * https://github.com/mathy/mathy_envs

Thank you very much for your patient guidance, but I find that I cannot complete the following test independently.
I want to implement the following step calculation of the formula, eg: `5+2*3-2*(3-1)`, expected output step-by-step:
First step: `5+2*3-2*2`;
Second step: `5+6-4`;
Final step: `7`;
If I wanted to implement the above example, how would I do it? Please give a detailed code example, thank you！

**Comment by justindujardin** [comment]
> I want to implement the following step calculation of the formula, eg: `5+2*3-2*(3-1)`, expected output step-by-step:
> First step: `5+2*3-2*2`;
> Second step: `5+6-4`;
> Final step: `7`;
> If I wanted to implement the above example, how would I do it? Please give a detailed code example, thank you！

The example I gave you does not solve this problem specifically, but it includes all the code you should need to adjust it for your specific problem. Let me know how it goes, good luck!

**Comment by Godlikemandyy** [comment]
> > I want to implement the following step calculation of the formula, eg: `5+2*3-2*(3-1)`, expected output step-by-step:
> > First step: `5+2*3-2*2`;
> > Second step: `5+6-4`;
> > Final step: `7`;
> > If I wanted to implement the above example, how would I do it? Please give a detailed code example, thank you！
> 
> The example I gave you does not solve this problem specifically (but may work for it anyway). If it doesn't work out of the box, it includes all the code you should need to adjust it for your problem. Let me know how it goes, good luck!

Thank you very much for sacrificing your spare time to help me solve this problem, I tried to run the code, although the result is a little different from what I want, but it is very good, I will try again, I wish you all the best!

**Comment by Godlikemandyy** [comment]
> > I want to implement the following step calculation of the formula, eg: `5+2*3-2*(3-1)`, expected output step-by-step:
> > First step: `5+2*3-2*2`;
> > Second step: `5+6-4`;
> > Final step: `7`;
> > If I wanted to implement the above example, how would I do it? Please give a detailed code example, thank you！
> 
> The example I gave you does not solve this problem specifically (but may work for it anyway). If it doesn't work out of the box, it includes all the code you should need to adjust it for your problem. Let me know how it goes, good luck!

Thank you very much for sacrificing your spare time to help me solve this problem, I tried to run the code, the results are useful. I also want to apply this method to the equation, what do I have to do to get the following result:
`equation: 2x+3x=5
step1: (2+3)*x=5;
step2: 5x=5;
step3: x=1`
Please take the trouble to guide me again, thank you very much！

**Comment by Godlikemandyy** [comment]
> > > I want to implement the following step calculation of the formula, eg: `5+2*3-2*(3-1)`, expected output step-by-step:
> > > First step: `5+2*3-2*2`;
> > > Second step: `5+6-4`;
> > > Final step: `7`;
> > > If I wanted to implement the above example, how would I do it? Please give a detailed code example, thank you！
> > 
> > 
> > The example I gave you does not solve this problem specifically (but may work for it anyway). If it doesn't work out of the box, it includes all the code you should need to adjust it for your problem. Let me know how it goes, good luck!
> 
> Thank you very much for sacrificing your spare time to help me solve this problem, I tried to run the code, the results are useful. I also want to apply this method to the equation, what do I have to do to get the following result: `equation: 2x+3x=5 step1: (2+3)*x=5; step2: 5x=5; step3: x=1` Please take the trouble to guide me again, thank you very much！

我尝试用上述代码测试equation: `2x+3x=5`，但是得到一下错误：
`STEP[0]: input                     | 2x + 3x = 5
STEP[1]: Distributive Factoring    | (2 + 3) * x = 5
Traceback (most recent call last):
  File "/Users/dongyangyang/Documents/dongao_dyy/projects/formula_solver/step_by_step.py", line 69, in <module>
    simplify_polynomial()
  File "/Users/dongyangyang/Documents/dongao_dyy/projects/formula_solver/step_by_step.py", line 50, in simplify_polynomial
    while not is_simplified(expression) and steps < limit:
  File "/Users/dongyangyang/Documents/dongao_dyy/projects/formula_solver/step_by_step.py", line 29, in is_simplified
    if not util.is_preferred_term_form(term):
  File "/opt/miniconda3/envs/solver/lib/python3.9/site-packages/mathy_core/util.py", line 314, in is_preferred_term_form
    if not is_simple_term(expression):
  File "/opt/miniconda3/envs/solver/lib/python3.9/site-packages/mathy_core/util.py", line 280, in is_simple_term
    sub_terms = get_sub_terms(node)
  File "/opt/miniconda3/envs/solver/lib/python3.9/site-packages/mathy_core/util.py", line 239, in get_sub_terms
    assert current is None or isinstance(
AssertionError: get_sub_terms(5x = 5) Expected Mul/Div/Power. Found: <class 'mathy_core.expressions.EqualExpression'>`

**Comment by Godlikemandyy** [comment]
> > > I want to implement the following step calculation of the formula, eg: `5+2*3-2*(3-1)`, expected output step-by-step:
> > > First step: `5+2*3-2*2`;
> > > Second step: `5+6-4`;
> > > Final step: `7`;
> > > If I wanted to implement the above example, how would I do it? Please give a detailed code example, thank you！
> > 
> > 
> > The example I gave you does not solve this problem specifically (but may work for it anyway). If it doesn't work out of the box, it includes all the code you should need to adjust it for your problem. Let me know how it goes, good luck!
> 
> Thank you very much for sacrificing your spare time to help me solve this problem, I tried to run the code, the results are useful. I also want to apply this method to the equation, what do I have to do to get the following result: `equation: 2x+3x=5 step1: (2+3)*x=5; step2: 5x=5; step3: x=1` Please take the trouble to guide me again, thank you very much！

I tried to test equation: `2x+3x=5` with the above code, but got the following error:
`STEP[0]: input                     | 2x + 3x = 5    

STEP[1]: Distributive Factoring    | (2 + 3) * x = 5     

Traceback (most recent call last):
  File "/Users/dongyangyang/Documents/dongao_dyy/projects/formula_solver/step_by_step.py", line 69, in <module>
    simplify_polynomial()
  File "/Users/dongyangyang/Documents/dongao_dyy/projects/formula_solver/step_by_step.py", line 50, in simplify_polynomial
    while not is_simplified(expression) and steps < limit:
  File "/Users/dongyangyang/Documents/dongao_dyy/projects/formula_solver/step_by_step.py", line 29, in is_simplified
    if not util.is_preferred_term_form(term):
  File "/opt/miniconda3/envs/solver/lib/python3.9/site-packages/mathy_core/util.py", line 314, in is_preferred_term_form
    if not is_simple_term(expression):
  File "/opt/miniconda3/envs/solver/lib/python3.9/site-packages/mathy_core/util.py", line 280, in is_simple_term
    sub_terms = get_sub_terms(node)
  File "/opt/miniconda3/envs/solver/lib/python3.9/site-packages/mathy_core/util.py", line 239, in get_sub_terms
    assert current is None or isinstance(
AssertionError: get_sub_terms(5x = 5) Expected Mul/Div/Power. Found: <class 'mathy_core.expressions.EqualExpression'>`

**Comment by Godlikemandyy** [comment]
> > > I want to implement the following step calculation of the formula, eg: `5+2*3-2*(3-1)`, expected output step-by-step:
> > > First step: `5+2*3-2*2`;
> > > Second step: `5+6-4`;
> > > Final step: `7`;
> > > If I wanted to implement the above example, how would I do it? Please give a detailed code example, thank you！
> > 
> > 
> > The example I gave you does not solve this problem specifically (but may work for it anyway). If it doesn't work out of the box, it includes all the code you should need to adjust it for your problem. Let me know how it goes, good luck!
> 
> Thank you very much for sacrificing your spare time to help me solve this problem, I tried to run the code, the results are useful. I also want to apply this method to the equation, what do I have to do to get the following result: 
`equation: 2x+3x=5 
step1: (2+3)*x=5; 
step2: 5x=5; 
step3: x=1`
I tried to test with the above code, but I got the following error, how to fix it?
`STEP[0]: input                     | 2x + 3x = 5
STEP[1]: Distributive Factoring    | (2 + 3) * x = 5
Traceback (most recent call last):
  File "/Users/dongyangyang/Documents/dongao_dyy/projects/formula_solver/step_by_step.py", line 69, in <module>
    simplify_polynomial()
  File "/Users/dongyangyang/Documents/dongao_dyy/projects/formula_solver/step_by_step.py", line 50, in simplify_polynomial
    while not is_simplified(expression) and steps < limit:
  File "/Users/dongyangyang/Documents/dongao_dyy/projects/formula_solver/step_by_step.py", line 29, in is_simplified
    if not util.is_preferred_term_form(term):
  File "/opt/miniconda3/envs/solver/lib/python3.9/site-packages/mathy_core/util.py", line 314, in is_preferred_term_form
    if not is_simple_term(expression):
  File "/opt/miniconda3/envs/solver/lib/python3.9/site-packages/mathy_core/util.py", line 280, in is_simple_term
    sub_terms = get_sub_terms(node)
  File "/opt/miniconda3/envs/solver/lib/python3.9/site-packages/mathy_core/util.py", line 239, in get_sub_terms
    assert current is None or isinstance(
AssertionError: get_sub_terms(5x = 5) Expected Mul/Div/Power. Found: <class 'mathy_core.expressions.EqualExpression'>`

**Comment by justindujardin** [comment]
> I also want to apply this method to the equation, what do I have to do to get the following result:
> equation: 2x+3x=5  step1: (2+3)*x=5;  step2: 5x=5;  step3: x=1
> I tried to test with the above code, but I got the following error, how to fix it?

Sorry, you're reaching beyond the limitations of the current mathy_core code. It has support for balanced move rules, but it looks like the util for finding preferred terms needs to be updated. 

> if not util.is_preferred_term_form(term):
> File "/opt/miniconda3/envs/solver/lib/python3.9/site-packages/mathy_core/util.py", line 314, in is_preferred_term_form
> if not is_simple_term(expression):
> File "/opt/miniconda3/envs/solver/lib/python3.9/site-packages/mathy_core/util.py", line 280, in is_simple_term
> sub_terms = get_sub_terms(node)
> File "/opt/miniconda3/envs/solver/lib/python3.9/site-packages/mathy_core/util.py", line 239, in get_sub_terms
> assert current is None or isinstance(
> AssertionError: get_sub_terms(5x = 5) Expected Mul/Div/Power. Found: <class 'mathy_core.expressions.EqualExpression'

Unfortunately, I can't help you with this further unless you make progress on your own. I love for people to use Mathy, but I can't provide step-by-step features and development for specific problems. That's why Mathy is open-source, so others can contribute to making it better. 

The issue you're running into is that I added the balanced move rule for dealing with equations relatively late in development and never fully integrated it into the existing environments. The assertion error is likely because get_sub_terms needs adjusting to deal with EqualExpression nodes in the tree.

**Comment by Godlikemandyy** [comment]
> > I also want to apply this method to the equation, what do I have to do to get the following result:
> > equation: 2x+3x=5  step1: (2+3)*x=5;  step2: 5x=5;  step3: x=1
> > I tried to test with the above code, but I got the following error, how to fix it?
> 
> Sorry, you're reaching beyond the limitations of the current mathy_core code. It has support for balanced move rules, but it looks like the util for finding preferred terms needs to be updated.
> 
> > if not util.is_preferred_term_form(term):
> > File "/opt/miniconda3/envs/solver/lib/python3.9/site-packages/mathy_core/util.py", line 314, in is_preferred_term_form
> > if not is_simple_term(expression):
> > File "/opt/miniconda3/envs/solver/lib/python3.9/site-packages/mathy_core/util.py", line 280, in is_simple_term
> > sub_terms = get_sub_terms(node)
> > File "/opt/miniconda3/envs/solver/lib/python3.9/site-packages/mathy_core/util.py", line 239, in get_sub_terms
> > assert current is None or isinstance(
> > AssertionError: get_sub_terms(5x = 5) Expected Mul/Div/Power. Found: <class 'mathy_core.expressions.EqualExpression'
> 
> Unfortunately, I can't help you with this further unless you make progress on your own. I love for people to use Mathy, but I can't provide step-by-step features and development for specific problems. That's why Mathy is open-source, so others can contribute to making it better.
> 
> The issue you're running into is that I added the balanced move rule for dealing with equations relatively late in development and never fully integrated it into the existing environments. The assertion error is likely because get_sub_terms needs adjusting to deal with EqualExpression nodes in the tree.
> 
> You could start here with the tests for that function: https://github.com/mathy/mathy_core/blob/master/tests/test_util.py#L13C31-L34

Thank you very much for your guidance. I will try to solve it by myself.

**Comment by justindujardin** [comment]
Best of luck, let us know how it turns out! I'll close this issue for now and leave the links:

- https://mathy.ai/examples/heuristics/
- https://mathy.ai/examples/mathy_ppo/
- https://mathy.ai/examples/swarm_solver/

The first one is similar to what I posted here for you, and the other two are automated solvers using machine learning and planning algorithms.
